# Generated by Django 5.1 on 2025-02-22 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_goal_achieved_goal_progress'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='goal',
            name='name',
            field=models.CharField(default='Моя цель', max_length=255),
            preserve_default=False,
        ),
    ]
